
name: Release MapLibre Native Core

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create maplibre-native-headers.tar.gz
        run: tar czf maplibre-native-headers.tar.gz include

      - name: Create Release
        run: |
          gh release create core-${{ github.sha }} \
            --draft=false \
            --prerelease=false \
            --latest=false \
            --title "core-${{ github.sha }}" \
            maplibre-native-headers.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    needs: [create-release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build mbgl-core for macOS
        run: |
          cmake --preset macos-core
          cmake --build --preset macos-core

      - name: Rename artifact
        run: cp build-macos/libmbgl-core.a libmaplibre-native-core-macos-arm64-metal.a

      - name: Upload macOS artifact
        run: gh release upload core-${{ github.sha }} libmaplibre-native-core-macos-arm64-metal.a
        env:
          GH_TOKEN: ${{ github.token }}

